### ISSUE TITLE
Use org.freedesktop.Sdk.Extension.rust-stable instead of manually downloading a toolchain binary

### ISSUE THREAD

**Issue by linkmauve** [flathub/io.missioncenter.MissionCenter#12]
This binary is very much impossible to audit, and the SDK already provides the same feature.

**Comment by kicsyromy** [comment]
I need a Rust toolchain the provides both `glibc` and `musl libc` compatibility.

The Gatherer, a binary that is run outside of the sandbox, needs to maintain compatibility with an old version of `glibc` and `musl libc`, to ensure compatibility with a wide range of Linux distrubutions.
