### ISSUE TITLE
Stop building musl

### ISSUE THREAD

**Issue by linkmauve** [flathub/io.missioncenter.MissionCenter#13]
The SDK you are building against provides glibc, which makes it a much more viable target than musl.

**Comment by kicsyromy** [comment]
The Gatherer, a binary that is run outside of the sandbox, needs to maintain compatibility with an old version of `glibc` and `musl libc`, to ensure compatibility with a wide range of Linux distrubutions.

Also, I use `musl libc` to build a static version `dmidecode`, that is executed outside of the sandbox. Again, done for compatibility.
