### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by tychart** [flathub/io.missioncenter.MissionCenter#23]
First of all, I love the project, and the UI layout looks amazing. I have noticed that when I have Mission Center running for long periods of time (multiple days), it takes up tons of my ram (4-6 GB out of 16 GB). When I close the program and restart it the problem goes away, but that is not ideal. I don't know if this is an intended thing, maybe keeping all the logs in memory has some benefit I don't realize. Or maybe this is a memory leak, but I would appreciate a fix or an explanation. 

Thanks! Again, amazing product, just eats up my memory over time, attached are screenshots after it has been up for probably 3 days straight.

Ps, my I am running Ubuntu 23.10, and have a 12th Gen Intel® Core™ i5-12400 CPU with 16GB ddr4 RAM in case that is relevent

![Screenshot from 2024-04-11 18-18-26](https://github.com/flathub/io.missioncenter.MissionCenter/assets/13421578/bface27d-ee22-45f7-b1d8-66d08b1a9947)
![Screenshot from 2024-04-11 18-22-11](https://github.com/flathub/io.missioncenter.MissionCenter/assets/13421578/019cc6a5-7ded-49fe-82bc-4d78cff8aa7c)
![Screenshot from 2024-04-11 18-22-38](https://github.com/flathub/io.missioncenter.MissionCenter/assets/13421578/b0d485db-dc71-4949-9f55-b8919129f645)

**Comment by kicsyromy** [comment]
Thanks for the report. Glad you're finding the app useful.

This is a [known issue](https://gitlab.com/mission-center-devs/mission-center/-/issues/61), and the hope is that with the latest changes in `main` it should be somewhat mitigated.

**Comment by kicsyromy** [comment]
Closing in favor of the issue on GitLab. Thanks again for the report, feel welcome to join the discussion on GitLab.
