### ISSUE TITLE
Feature - adding a Restart process into the app sections

### ISSUE THREAD

**Issue by lebgdu543** [flathub/io.missioncenter.MissionCenter#25]
It allows the user to _restart_ the application.
i don't find the way to do in the pull requests section on github and on gitlab to.

**Comment by kicsyromy** [comment]
So sorry, I completely missed this issue.

Sounds like a good idea.

I opened an issue on out GitLab: https://gitlab.com/mission-center-devs/mission-center/-/issues/208

Please join the conversation there. If you need help with contributing this feature to the app I'll gladly assist you.

Thanks again for bringing up the issue.

**Comment by kicsyromy** [comment]
Closing in favor of GitLab ticket.
